name: Deploy site

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

  workflow_run:
    branches: ["main"]
    workflows: ["Update data"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      
      - name: Install dependencies
        run: npm i
        
      - name: Set Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Build & push starboard
        continue-on-error: true
        run: |
          node starboard/build.js
          git add .
          git commit -m "chore: build starboard.json"
          git push
    
      - name: Build site
        run: npm run build
    
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build